[build]
nixPkgs = ["nodejs"]

[phases.build]
commands = [
  "cd FRONTEND && npm install && npm run build -- --configuration=production",
  "cd BACKEND && npm install"
]

[start]
command = "cd BACKEND && node index.js"